version: 2
updates:
  # All Node/pnpm deps in ONE PR
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Athens"
    groups:
      everything-npm:
        applies-to: version-updates
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Europe/Athens"
    groups:
      everything-actions:
        applies-to: version-updates
        patterns: ["*"]
